Check if requirement is set before matching version.
If requirement is nil and you try to .match a regex it will error:
`range_requirement?': undefined method `match' for nil:NilClass